"""Active Validation Swarm Data Models for NSAT."""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional
from urllib.parse import urlparse
from pydantic import BaseModel, Field

from nsat.normalization.models import CanonicalFinding


class AgentResultStatus(str, Enum):
    """Execution status returned by validation agents."""
    VALIDATED = "VALIDATED"
    NOT_VALIDATED = "NOT_VALIDATED"
    POTENTIAL = "POTENTIAL"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    BLOCKED = "BLOCKED"
    ERROR = "ERROR"


class ValidationEvidence(BaseModel):
    """
    Structured evidence generated by an active validation agent probe.
    Never stores sensitive raw bodies; credentials and tokens are redacted.
    """
    agent: str
    target: str
    endpoint: str
    request_type: str  # e.g., "HTTP_GET", "HTTP_POST", "TCP_CONNECT", "WS_PROBE", "INSPECT"
    safe_test_description: str
    observed_response: str
    status: AgentResultStatus
    confidence: float = Field(ge=0.0, le=1.0)
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    related_finding_id: Optional[str] = None
    details: dict[str, Any] = Field(default_factory=dict)


class TargetScope(BaseModel):
    """
    Target authorization and scope enforcement policy.
    Ensures probes are only run against authorized local or test endpoints.
    """
    target: str
    explicitly_authorized: bool = False
    allowed_hosts: list[str] = Field(
        default_factory=lambda: ["localhost", "127.0.0.1", "::1", "0.0.0.0", "testserver"]
    )
    allow_private_ranges: bool = False

    def is_authorized(self) -> bool:
        """Verify that the target falls strictly within the authorized boundary."""
        if not self.target:
            return False

        parsed = urlparse(self.target if "://" in self.target else f"http://{self.target}")
        host = (parsed.hostname or "").lower()

        # Localhost/loopback is allowed by default
        if host in self.allowed_hosts:
            return True

        # Custom explicit authorization required for external / remote addresses
        if self.explicitly_authorized:
            return True

        return False


class SwarmConfig(BaseModel):
    """Runtime limits and bounded execution budget for the validation swarm."""
    agent_timeout: float = 5.0
    request_timeout: float = 2.0
    max_validation_attempts: int = 5
    max_payload_size: int = 4096
    global_target_budget: int = 60
    max_concurrency: int = 4
    demo_mode: bool = False


class AgentExecutionResult(BaseModel):
    """Outcome of a single validation agent execution."""
    agent_name: str
    status: AgentResultStatus
    evidence: list[ValidationEvidence] = Field(default_factory=list)
    upgraded_finding_ids: list[str] = Field(default_factory=list)
    new_findings: list[CanonicalFinding] = Field(default_factory=list)
    error_message: Optional[str] = None
    duration_seconds: float = 0.0


class SwarmResult(BaseModel):
    """
    Aggregate result from running the Active Validation Swarm.
    Prepares a clean handoff structure for Phase 4 Correlation & AI layers.
    """
    target: str
    scope_enforced: bool = True
    agents_selected: list[str] = Field(default_factory=list)
    agents_skipped: list[tuple[str, str]] = Field(default_factory=list)
    agent_results: dict[str, AgentExecutionResult] = Field(default_factory=dict)
    all_evidence: list[ValidationEvidence] = Field(default_factory=list)
    findings: list[CanonicalFinding] = Field(default_factory=list)
    upgraded_count: int = 0
    new_findings_count: int = 0
    duration_seconds: float = 0.0

    # Phase 4 handoff interface (Correlation Engine / AI Layer)
    correlation_handoff: dict[str, Any] = Field(default_factory=dict)
