"""Data schemas and lifecycle contracts for NSAT Remediation & Verification."""

from datetime import datetime, timezone
from enum import Enum
from pathlib import Path
from typing import Any, Optional
from pydantic import BaseModel, Field


class RemediationStatus(str, Enum):
    """Lifecycle states of an autonomous remediation action."""
    PLANNED = "PLANNED"
    BACKED_UP = "BACKED_UP"
    APPROVED = "APPROVED"
    APPLIED = "APPLIED"
    TESTING = "TESTING"
    RESCANNING = "RESCANNING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    ROLLING_BACK = "ROLLING_BACK"
    ROLLED_BACK = "ROLLED_BACK"
    ROLLBACK_CONFLICT = "ROLLBACK_CONFLICT"


class VerificationOutcome(str, Enum):
    """Possible outcomes when evaluating post-remediation re-scan."""
    RESOLVED = "RESOLVED"
    PARTIALLY_RESOLVED = "PARTIALLY_RESOLVED"
    STILL_PRESENT = "STILL_PRESENT"
    REGRESSION = "REGRESSION"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"
    ROLLED_BACK = "ROLLED_BACK"
    ROLLBACK_CONFLICT = "ROLLBACK_CONFLICT"


class SnapshotMetadata(BaseModel):
    """Audit snapshot metadata captured before any file modification."""
    remediation_id: str
    finding_id: str
    audit_id: Optional[str] = None
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    repository_root: str
    affected_files: list[str]
    original_hashes: dict[str, str] = Field(
        description="Map of relative file paths to pre-patch SHA-256 digests"
    )
    post_patch_hashes: dict[str, str] = Field(
        default_factory=dict,
        description="Map of relative file paths to post-patch SHA-256 digests",
    )
    proposed_patch: str
    status: RemediationStatus = RemediationStatus.BACKED_UP
    backup_dir: str


class RemediationProposal(BaseModel):
    """Structured proposal generated by Kimi-K3 or deterministic rules."""
    finding_id: str
    root_cause: str
    recommended_change: str
    affected_file: str
    affected_lines: Any = "N/A"
    proposed_patch: str
    original_snippet: str
    replacement_snippet: str
    reason: str
    potential_side_effects: str
    verification_plan: str


class VerificationReport(BaseModel):
    """Authoritative before-and-after verification report."""
    remediation_id: str
    finding_id: str
    previous_status: str
    current_status: str
    previous_risk_score: int
    current_risk_score: int
    previous_risk_level: str
    current_risk_level: str
    resolved: bool
    outcome: VerificationOutcome
    tests_passed: bool
    re_scan_evidence: list[str] = Field(default_factory=list)
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    rollback_performed: bool = False
    rollback_status: Optional[str] = None
