"""
ReportLab PDF Renderer for NSAT Remediation Change Reports.

Produces high-fidelity, professional, multi-page security remediation reports
with visual hierarchy, severity badges, structured tables, monospace code diffs,
and audit sign-off blocks.
"""

from __future__ import annotations

import html
import io
import re
from pathlib import Path
from typing import Optional

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from nsat.remediation_report.models import RemediationReportContext


# ── Color Palette ─────────────────────────────────────────────────────────────

PRIMARY_COLOR = colors.HexColor("#1A365D")      # Deep Navy
SECONDARY_COLOR = colors.HexColor("#2B6CB0")    # Slate Blue
TEXT_COLOR = colors.HexColor("#1A202C")         # Charcoal Dark
TEXT_MUTED = colors.HexColor("#718096")         # Muted Gray
BG_LIGHT = colors.HexColor("#F8FAFC")           # Off-white / light slate
BG_ALT = colors.HexColor("#EDF2F7")             # Alt row light
BORDER_COLOR = colors.HexColor("#CBD5E1")       # Border slate
CODE_BG = colors.HexColor("#0F172A")            # Dark terminal slate
CODE_TEXT = colors.HexColor("#38BDF8")          # Cyan monospace
CODE_ADD = colors.HexColor("#22C55E")           # Green add
CODE_DEL = colors.HexColor("#EF4444")           # Red del

SEVERITY_COLORS = {
    "CRITICAL": colors.HexColor("#DC2626"),
    "HIGH": colors.HexColor("#EA580C"),
    "MEDIUM": colors.HexColor("#D97706"),
    "LOW": colors.HexColor("#0284C7"),
    "INFO": colors.HexColor("#64748B"),
}

STATUS_COLORS = {
    "PROPOSED": colors.HexColor("#2563EB"),
    "APPROVED": colors.HexColor("#16A34A"),
    "APPLIED": colors.HexColor("#0D9488"),
    "VERIFIED": colors.HexColor("#059669"),
    "REJECTED": colors.HexColor("#DC2626"),
    "ROLLED_BACK": colors.HexColor("#9333EA"),
    "ROLLBACK_CONFLICT": colors.HexColor("#B91C1C"),
    "VERIFICATION_FAILED": colors.HexColor("#C026D3"),
}


# ── Two-Pass Canvas for Page Numbering ─────────────────────────────────────────

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to dynamically compute and print 'Page X of Y'
    along with running header and footer on each page.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states: list[dict] = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(TEXT_MUTED)

        # Running Header (pages 2+)
        if self._pageNumber > 1:
            self.drawString(54, 11 * inch - 36, "NSAT Security Audit — AI Remediation Change Report")
            self.setStrokeColor(BORDER_COLOR)
            self.setLineWidth(0.5)
            self.line(54, 11 * inch - 42, 8.5 * inch - 54, 11 * inch - 42)

        # Running Footer (all pages)
        footer_text = f"Confidential — Internal Security Review Only  |  Page {self._pageNumber} of {page_count}"
        self.drawRightString(8.5 * inch - 54, 30, footer_text)
        self.drawString(54, 30, "Generated by NSAT Automated Security Engine")
        self.setStrokeColor(BORDER_COLOR)
        self.setLineWidth(0.5)
        self.line(54, 42, 8.5 * inch - 54, 42)

        self.restoreState()


# ── ReportLab Renderer ────────────────────────────────────────────────────────

class ReportLabRenderer:
    """Renders a RemediationReportContext into an audit-ready PDF document."""

    @classmethod
    def _xml(cls, text: Optional[str]) -> str:
        """Escape raw string for safe ReportLab XML Paragraph rendering."""
        if not text:
            return ""
        return html.escape(str(text))

    @classmethod
    def _break_long_words(cls, text: str, max_chunk: int = 40) -> str:
        """Insert zero-width breaks into long hashes/paths so tables wrap cleanly."""
        if not text:
            return ""
        return re.sub(rf"(\S{{{max_chunk}}})", r"\1 ", text)

    @classmethod
    def _create_styles(cls) -> dict[str, ParagraphStyle]:
        """Build typography stylesheet for the document."""
        base = getSampleStyleSheet()

        styles = {
            "DocTitle": ParagraphStyle(
                "DocTitle",
                parent=base["Title"],
                fontName="Helvetica-Bold",
                fontSize=20,
                leading=24,
                textColor=PRIMARY_COLOR,
                alignment=0,
                spaceAfter=4,
            ),
            "DocSubtitle": ParagraphStyle(
                "DocSubtitle",
                parent=base["Normal"],
                fontName="Helvetica",
                fontSize=9,
                leading=12,
                textColor=TEXT_MUTED,
                spaceAfter=12,
            ),
            "SectionHeader": ParagraphStyle(
                "SectionHeader",
                parent=base["Heading2"],
                fontName="Helvetica-Bold",
                fontSize=12,
                leading=16,
                textColor=PRIMARY_COLOR,
                spaceBefore=12,
                spaceAfter=6,
                keepWithNext=True,
            ),
            "SubsectionHeader": ParagraphStyle(
                "SubsectionHeader",
                parent=base["Heading3"],
                fontName="Helvetica-Bold",
                fontSize=10,
                leading=14,
                textColor=SECONDARY_COLOR,
                spaceBefore=8,
                spaceAfter=4,
                keepWithNext=True,
            ),
            "Body": ParagraphStyle(
                "Body",
                parent=base["BodyText"],
                fontName="Helvetica",
                fontSize=9,
                leading=13,
                textColor=TEXT_COLOR,
                spaceAfter=6,
            ),
            "BodyBold": ParagraphStyle(
                "BodyBold",
                parent=base["BodyText"],
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=13,
                textColor=TEXT_COLOR,
            ),
            "CalloutText": ParagraphStyle(
                "CalloutText",
                parent=base["Normal"],
                fontName="Helvetica-Oblique",
                fontSize=9,
                leading=13,
                textColor=TEXT_COLOR,
            ),
            "TableHeader": ParagraphStyle(
                "TableHeader",
                parent=base["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8.5,
                leading=11,
                textColor=colors.white,
            ),
            "TableCell": ParagraphStyle(
                "TableCell",
                parent=base["Normal"],
                fontName="Helvetica",
                fontSize=8,
                leading=11,
                textColor=TEXT_COLOR,
            ),
            "TableCellBold": ParagraphStyle(
                "TableCellBold",
                parent=base["Normal"],
                fontName="Helvetica-Bold",
                fontSize=8,
                leading=11,
                textColor=TEXT_COLOR,
            ),
            "CodeBlock": ParagraphStyle(
                "CodeBlock",
                parent=base["Normal"],
                fontName="Courier",
                fontSize=7.5,
                leading=10,
                textColor=CODE_TEXT,
            ),
            "MetaBadge": ParagraphStyle(
                "MetaBadge",
                parent=base["Normal"],
                fontName="Helvetica-Bold",
                fontSize=9,
                leading=12,
                textColor=colors.white,
                alignment=1,
            ),
        }
        return styles

    @classmethod
    def render_to_bytes(cls, ctx: RemediationReportContext) -> bytes:
        """Render context to in-memory PDF bytes."""
        buffer = io.BytesIO()
        cls._build_document(ctx, buffer)
        return buffer.getvalue()

    @classmethod
    def render_to_file(cls, ctx: RemediationReportContext, target_path: str | Path) -> Path:
        """Render context directly to a target PDF file on disk."""
        target = Path(target_path).resolve()
        target.parent.mkdir(parents=True, exist_ok=True)
        cls._build_document(ctx, str(target))
        return target

    @classmethod
    def _build_document(cls, ctx: RemediationReportContext, output_target) -> None:
        """Internal builder driving ReportLab document generation."""
        doc = SimpleDocTemplate(
            output_target,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54,
        )

        styles = cls._create_styles()
        story: list = []

        # ── 1. Document Header & Top Meta Banner ──────────────────────
        story.append(Paragraph("NSAT Remediation Change Report", styles["DocTitle"]))
        subtitle = (
            f"Report ID: <b>{cls._xml(ctx.report_id)}</b> &nbsp;|&nbsp; "
            f"Generated: {cls._xml(ctx.generated_at[:19].replace('T', ' '))} UTC &nbsp;|&nbsp; "
            f"Project: <b>{cls._xml(ctx.project_name or 'N/A')}</b>"
        )
        story.append(Paragraph(subtitle, styles["DocSubtitle"]))
        story.append(HRFlowable(width="100%", thickness=1.5, color=PRIMARY_COLOR, spaceAfter=8))

        # Severity & Status Pill Banner Table
        sev_color = SEVERITY_COLORS.get(ctx.severity.upper(), colors.HexColor("#64748B"))
        stat_color = STATUS_COLORS.get(ctx.status.upper(), colors.HexColor("#3B82F6"))

        banner_data = [
            [
                Paragraph("<b>FINDING ID</b>", styles["TableCellBold"]),
                Paragraph(f"<b>{cls._xml(ctx.finding_id)}</b>", styles["TableCellBold"]),
                Paragraph("<b>SEVERITY</b>", styles["TableCellBold"]),
                Paragraph(f"<b>{cls._xml(ctx.severity.upper())}</b>", styles["MetaBadge"]),
                Paragraph("<b>STATUS</b>", styles["TableCellBold"]),
                Paragraph(f"<b>{cls._xml(ctx.status.upper())}</b>", styles["MetaBadge"]),
            ]
        ]
        banner_table = Table(banner_data, colWidths=[70, 110, 60, 90, 55, 119])
        banner_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("BACKGROUND", (3, 0), (3, 0), sev_color),
                ("BACKGROUND", (5, 0), (5, 0), stat_color),
            ])
        )
        story.append(banner_table)
        story.append(Spacer(1, 10))

        # ── 2. Executive Summary ──────────────────────────────────────
        story.append(Paragraph("1. Executive Summary", styles["SectionHeader"]))
        exec_summary = ctx.ai_executive_summary or ctx.description or "No executive summary provided."
        summary_table = Table(
            [[Paragraph(cls._xml(exec_summary), styles["Body"])]],
            colWidths=[504],
        )
        summary_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("LINEBEFORE", (0, 0), (0, 0), 3, SECONDARY_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ])
        )
        story.append(summary_table)
        story.append(Spacer(1, 10))

        # ── 3. Finding Overview & Context ─────────────────────────────
        story.append(Paragraph("2. Finding Details & Context", styles["SectionHeader"]))
        loc_str = ctx.file_path or "N/A"
        if ctx.line_number:
            loc_str += f":{ctx.line_number}"
        if ctx.function_name:
            loc_str += f" (in `{ctx.function_name}`)"

        finding_meta_data = [
            [
                Paragraph("<b>Title:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.finding_title), styles["TableCell"]),
                Paragraph("<b>Category:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.category), styles["TableCell"]),
            ],
            [
                Paragraph("<b>Primary Location:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(loc_str), styles["TableCell"]),
                Paragraph("<b>Confidence:</b>", styles["TableCellBold"]),
                Paragraph(f"{ctx.confidence:.2f}", styles["TableCell"]),
            ],
            [
                Paragraph("<b>Risk Score:</b>", styles["TableCellBold"]),
                Paragraph(str(ctx.risk_score) if ctx.risk_score is not None else "N/A", styles["TableCell"]),
                Paragraph("<b>Priority:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.priority or "N/A"), styles["TableCell"]),
            ],
        ]

        if ctx.blast_radius_tier or ctx.correlated_attack_path:
            finding_meta_data.append([
                Paragraph("<b>Blast Radius:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.blast_radius_tier or "N/A"), styles["TableCell"]),
                Paragraph("<b>Attack Path:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.correlated_attack_path or "None"), styles["TableCell"]),
            ])

        meta_table = Table(finding_meta_data, colWidths=[95, 175, 80, 154])
        meta_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.white),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ])
        )
        story.append(meta_table)

        # Evidence Callout if available
        if ctx.evidence_summary and ctx.evidence_summary != "No structured evidence available.":
            story.append(Spacer(1, 6))
            story.append(Paragraph("<b>Detected Evidence:</b>", styles["SubsectionHeader"]))
            ev_table = Table([[Paragraph(cls._xml(ctx.evidence_summary), styles["TableCell"])]], colWidths=[504])
            ev_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
                    ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ])
            )
            story.append(ev_table)

        story.append(Spacer(1, 10))

        # ── 4. Technical Root Cause Analysis ──────────────────────────
        story.append(Paragraph("3. Technical Root Cause Analysis", styles["SectionHeader"]))
        rc_text = ctx.ai_root_cause_narrative or ctx.root_cause or "No detailed root cause analysis available."
        rc_formatted = cls._xml(rc_text).replace("\n", "<br/>")
        rc_table = Table([[Paragraph(rc_formatted, styles["Body"])]], colWidths=[504])
        rc_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ])
        )
        story.append(rc_table)
        story.append(Spacer(1, 10))

        # ── 5. Proposed Remediation Change & Security Rationale ────────
        story.append(Paragraph("4. Proposed Remediation Change & Rationale", styles["SectionHeader"]))

        # Why this change
        why_text = ctx.ai_why_this_change or ctx.reason or ctx.proposed_change_description
        if why_text:
            story.append(Paragraph("<b>Security Rationale:</b>", styles["SubsectionHeader"]))
            story.append(Paragraph(cls._xml(why_text).replace("\n", "<br/>"), styles["Body"]))

        # Affected Files Table
        if ctx.affected_files:
            story.append(Spacer(1, 4))
            story.append(Paragraph("<b>Affected Files & Cryptographic Fingerprints:</b>", styles["SubsectionHeader"]))
            file_rows = [
                [
                    Paragraph("File Path", styles["TableHeader"]),
                    Paragraph("Lines", styles["TableHeader"]),
                    Paragraph("Original Hash (SHA-256)", styles["TableHeader"]),
                    Paragraph("Post-Patch Hash (SHA-256)", styles["TableHeader"]),
                ]
            ]
            for af in ctx.affected_files:
                file_rows.append([
                    Paragraph(cls._xml(af.file_path), styles["TableCellBold"]),
                    Paragraph(cls._xml(af.relevant_lines or "All"), styles["TableCell"]),
                    Paragraph(cls._break_long_words(af.original_hash or "Pending"), styles["TableCell"]),
                    Paragraph(cls._break_long_words(af.post_patch_hash or "Pending"), styles["TableCell"]),
                ])
            file_table = Table(file_rows, colWidths=[164, 45, 145, 150])
            file_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
                    ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ])
            )
            story.append(file_table)

        # Code Diff / Proposed Patch Block
        if ctx.proposed_patch or (ctx.original_snippet and ctx.replacement_snippet):
            story.append(Spacer(1, 6))
            story.append(Paragraph("<b>Code Remediation Diff:</b>", styles["SubsectionHeader"]))

            diff_content = ctx.proposed_patch or (
                f"--- Original Snippet\n+++ Replacement Snippet\n"
                f"- {ctx.original_snippet}\n+ {ctx.replacement_snippet}"
            )
            # Format diff lines with colored spans
            diff_lines = []
            for line in diff_content.splitlines()[:60]:  # limit lines for PDF layout
                line_escaped = cls._xml(line).replace(" ", "&nbsp;")
                if line.startswith("+"):
                    diff_lines.append(f"<font color='#4ADE80'>{line_escaped}</font>")
                elif line.startswith("-"):
                    diff_lines.append(f"<font color='#F87171'>{line_escaped}</font>")
                elif line.startswith("@"):
                    diff_lines.append(f"<font color='#38BDF8'>{line_escaped}</font>")
                else:
                    diff_lines.append(f"<font color='#CBD5E1'>{line_escaped}</font>")

            diff_para = Paragraph("<br/>".join(diff_lines), styles["CodeBlock"])
            diff_table = Table([[diff_para]], colWidths=[504])
            diff_table.setStyle(
                TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), CODE_BG),
                    ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#334155")),
                    ("TOPPADDING", (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                ])
            )
            story.append(diff_table)

        # Potential side effects
        if ctx.potential_side_effects:
            story.append(Spacer(1, 6))
            story.append(
                Paragraph(
                    f"<b>Side Effects & Considerations:</b> {cls._xml(ctx.potential_side_effects)}",
                    styles["Body"],
                )
            )

        story.append(Spacer(1, 10))

        # ── 6. Safety, Backup & Rollback Protocol ─────────────────────
        story.append(Paragraph("5. Backup, Safety & Rollback Protocol", styles["SectionHeader"]))
        backup_rows = [
            [
                Paragraph("<b>Backup Status:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.backup_status), styles["TableCell"]),
                Paragraph("<b>Rollback Available:</b>", styles["TableCellBold"]),
                Paragraph("YES (Snapshot preserved)" if ctx.rollback_available else "NO", styles["TableCellBold"]),
            ],
            [
                Paragraph("<b>Backup Location:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.backup_location or "Created automatically upon patch execution"), styles["TableCell"]),
                Paragraph("<b>Remediation ID:</b>", styles["TableCellBold"]),
                Paragraph(cls._xml(ctx.remediation_id or "N/A"), styles["TableCell"]),
            ],
        ]
        backup_table = Table(backup_rows, colWidths=[100, 170, 110, 124])
        backup_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), BG_LIGHT),
                ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ])
        )
        story.append(backup_table)
        story.append(Spacer(1, 10))

        # ── 7. Verification Plan & Sign-off ───────────────────────────
        story.append(KeepTogether([
            Paragraph("6. Verification Plan & Human Sign-off", styles["SectionHeader"]),
            Paragraph(
                f"<b>Verification Steps:</b> {cls._xml(ctx.verification_plan or 'Perform regression tests and re-scan codebase with NSAT.')}",
                styles["Body"],
            ),
            Paragraph(
                f"<b>Recommendation:</b> {cls._xml(ctx.ai_final_recommendation or 'Review and approve patch.')}",
                styles["Body"],
            ),
            Spacer(1, 6),
            Paragraph("<b>Human Review & Approval Sign-off:</b>", styles["SubsectionHeader"]),
            Table(
                [
                    [
                        Paragraph("Reviewer Name", styles["TableHeader"]),
                        Paragraph("Role / Title", styles["TableHeader"]),
                        Paragraph("Decision", styles["TableHeader"]),
                        Paragraph("Date & Signature", styles["TableHeader"]),
                    ],
                    [
                        Paragraph("&nbsp;<br/>&nbsp;", styles["TableCell"]),
                        Paragraph("&nbsp;<br/>&nbsp;", styles["TableCell"]),
                        Paragraph("[ &nbsp; ] Approved &nbsp;&nbsp; [ &nbsp; ] Rejected", styles["TableCellBold"]),
                        Paragraph("&nbsp;<br/>&nbsp;", styles["TableCell"]),
                    ],
                ],
                colWidths=[140, 130, 114, 120],
                style=[
                    ("BACKGROUND", (0, 0), (-1, 0), PRIMARY_COLOR),
                    ("BOX", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                    ("INNERGRID", (0, 0), (-1, -1), 0.5, BORDER_COLOR),
                    ("TOPPADDING", (0, 0), (-1, -1), 4),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
                ],
            ),
        ]))

        doc.build(story, canvasmaker=NumberedCanvas)
